[package]
  cjc-version = "1.0.5"
  name = "midi"
  description = "CangjieMIDI - MIDI Script Language & Transcoding Tool"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
